In [1]:
"""For this application,

"https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0 " 
the link(above) used as a reference. 

"""
#To make some adjustments

!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.


In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

In [0]:
import sys
sys.path.insert(0, 'drive/Colab Notebooks') #add your google colab files path
#Finished the adjustments

In [5]:
#Let's learn where we are working on (CPU or GPU)
import tensorflow as tf
tf.test.gpu_device_name()
#İf you are working on CPU, You're gonna see that answer

''

In [2]:
import tensorflow as tf
tf.test.gpu_device_name()
#İt shows we are working on GPU

'/device:GPU:0'

## Unlike policy gradient methods, which attempt to learn functions which directly map an observation to an action, Q-Learning attempts to learn the value of being in a given state, and taking a specific action there. While both approaches ultimately allow us to take intelligent actions given a situation, the means of getting to that action differ significantly [link text](https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0)

In [0]:
import gym
import numpy as np

In [0]:
env=gym.make('FrozenLake-v0')

In [0]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [20]:
print ("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.348


In [21]:
print ("Final Q-Table Values")
print (Q)

Final Q-Table Values
[[3.46664620e-03 6.63966596e-02 2.57931413e-03 3.47844773e-03]
 [1.17742074e-04 1.65354677e-04 2.74433422e-04 1.93584694e-02]
 [9.98325442e-02 1.34716444e-03 6.84098839e-04 1.42643040e-03]
 [3.44161966e-04 5.59195484e-05 6.97290931e-05 1.34406671e-03]
 [8.64021185e-02 3.01733060e-03 2.59426228e-03 3.63885119e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.59880022e-01 2.24190875e-11 1.24383898e-03 6.70144281e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.03186344e-03 0.00000000e+00 6.39543659e-04 3.02420335e-01]
 [4.06189766e-04 6.68995773e-01 2.45018699e-03 8.16106138e-04]
 [8.99270949e-01 2.27226545e-04 0.00000000e+00 1.03452172e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.07253358e-03 7.11262930e-04 3.22567873e-01 1.75792945e-04]
 [0.00000000e+00 0.00000000e+00 9.94691919e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.